In [1]:
# report which features were selected by RFE
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.datasets import make_classification

In [2]:
# define dataset
# make_classification
# (샘플,특징의 수, 주요특징의 개수, 중복가능 횟수,난수생성(같으면 같은 난수))
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5,
                           n_redundant=5, random_state=42)

In [3]:
X.shape

(1000, 10)

In [4]:
y.shape

(1000,)

In [20]:
X

array([[-0.05935747, -0.81075922, -1.46291185, ..., -0.71333492,
        -0.38779067,  0.30975536],
       [ 1.35040799,  4.22073174,  1.56416182, ..., -1.35261676,
         0.56164546,  3.05553349],
       [ 1.06995768,  3.02959431, -2.68448393, ...,  1.67460575,
         1.4897756 ,  0.03734801],
       ...,
       [ 1.32117879,  3.00727694,  0.242322  , ..., -0.802865  ,
         0.67092995,  2.27887143],
       [-0.52716176,  0.70840414, -1.69716553, ..., -0.58513067,
        -0.57348277, -0.17506291],
       [-1.72169116, -0.78642113, -1.12858852, ...,  2.46859264,
        -0.00922643, -2.81226403]])

In [5]:
# define RFE
# pca = PCA(estimator=DecisionTreeClassifier(), n_features_to_select=5)

In [7]:
trans=PCA(n_components = 3)

In [19]:
type(X)

numpy.ndarray

In [8]:
X_dim=trans.fit_transform(X)

In [9]:
X_dim.shape[1]

In [21]:
X_dim

array([[ 2.51303178e-01, -1.00943303e+00, -4.88820624e-01],
       [-7.46995238e+00, -1.18205155e+00,  9.31007918e-01],
       [-2.75328534e+00,  6.40100700e+00, -5.48175385e-01],
       ...,
       [-5.20538609e+00,  4.44188488e-03, -1.04591442e-01],
       [-6.86710549e-01,  8.19766468e-01,  1.45121320e+00],
       [ 1.27014720e+00,  2.68262341e+00,  1.90908455e+00]])

In [22]:
# fit RFE
# pca.fit(X, y)
print(X_dim[:3,:])

[[ 0.25130318 -1.00943303 -0.48882062]
 [-7.46995238 -1.18205155  0.93100792]
 [-2.75328534  6.401007   -0.54817539]]


In [23]:
# summarize all features
X_dim.shape[1]

3

In [ ]:
# pca.ranking_[5]

In [ ]:
# pca.support_[5]

In [24]:
trans.fit(X_dim)

PCA(n_components=3)

In [13]:
pca = pd.DataFrame(data=X_dim, columns = ['principal component1', 'principal component2',
                                          'principal component3'])

In [29]:
pca

principal component1  principal component2  principal component3
0                0.251303             -1.009433             -0.488821
1               -7.469952             -1.182052              0.931008
2               -2.753285              6.401007             -0.548175
3               -0.157705              0.562171              0.802498
4               -0.767812             -3.430093              2.044420
..                    ...                   ...                   ...
995              6.550398              0.725700             -3.871207
996              7.352176             -0.625899              0.493420
997             -5.205386              0.004442             -0.104591
998             -0.686711              0.819766              1.451213
999              1.270147              2.682623              1.909085

[1000 rows x 3 columns]

In [32]:
trans.explained_variance_ratio_

array([0.63054713, 0.22624084, 0.14321202])

In [33]:
trans.components_

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  1.00000000e+00,  1.11022302e-15],
       [ 0.00000000e+00, -1.11022302e-15,  1.00000000e+00]])

In [17]:
type(trans)

sklearn.decomposition._pca.PCA